package euler

import org.scalatest.matchers.ShouldMatchers
import org.scalatest.{Tag, FunSuite}

class ExpectedResults extends FunSuite with ShouldMatchers {

  test("1: Add all the natural numbers below one thousand that are multiples of 3 or 5", Tag("1")) {
    Problem1.solve should be(233168)
  }

  test("2: Add even valued fibonacci numbers below 4M", Tag("2")) {
    Problem2.solve should be(4613732)
  }

  test("3: Find the largest prime factor of a composite number 600851475143", Tag("3")) {
    Problem3.solve should be(6857)
  }

  test("4: Find the largest palindrome made from the product of two 3-digit numbers", Tag("4")) {
    Problem4.solve should be(906609)
  }

  test("5: What is the smallest number divisible by each of the numbers 1 to 20?", Tag("5")) {
    Problem5.solve should be(232792560)
  }

  test("6: What is the difference between the sum of the squares and the square of the sums?", Tag("6")) {
    Problem6.solve should be(25164150)
  }

  test("7: Find the 10001st prime.", Tag("7")) {
    Problem7.solve should be(104743)
  }

  test("8: Discover the largest product of five consecutive digits in the 1000-digit number.", Tag("8")) {
    Problem8.solve should be(40824)
  }

  test("9: Find the only Pythagorean triplet, {a, b, c}, for which a + b + c = 1000.", Tag("9")) {
    Problem9.solve should be(31875000)
  }

  test("10: Calculate the sum of all the primes below two million", Tag("10")) {
    Problem10.solve should be(142913828922L)
  }

  test("11: What is the greatest product of four adjacent numbers on the same straight line in the 20 by 20 grid?", Tag("11")) {
    Problem11.solve should be(70600674)
  }

  test("12: What is the value of the first triangle number to have over five hundred divisors?", Tag("12")) {
    Problem12.solve should be(76576500)
  }

  test("13: Find the first ten digits of the sum of one-hundred 50-digit numbers.", Tag("13")) {
    Problem13.solve should be(5537376230L)
  }

  test("14: Find the longest sequence using a starting number under one million", Tag("14")) {
    Problem14.solve should be(837799)
  }

  test("15: Starting in the top left corner in a 20 by 20 grid, how many routes are there to the bottom right corner?", Tag("15")) {
    Problem15.solve should be(137846528820L)
  }

  test("16: What is the sum of the digits of the number 21000?", Tag("16")) {
    Problem16.solve should be(1366)
  }

  test("17: How many letters would be needed to write all the numbers in words from 1 to 1000?", Tag("17")) {
    Problem17.solve should be(21124)
  }

  test("18: Find the maximum sum travelling from the top of the triangle to the base (small size)", Tag("18")) {
    Problem18.solve should be(1074)
  }

  test("67: Find the maximum sum travelling from the top of the triangle to the base (large size)", Tag("67")) {
    Problem67.solve should be(7273)
  }

  test("19: How many Sundays fell on the first of the month during the twentieth century", Tag("19")) {
    Problem19.solve should be(171)
  }

  test("20: Find the sum of digits in 100!", Tag("20")) {
    Problem20.solve should be(648)
  }

  test("22: What is the total of all the name scores in the file of first names?", Tag("22")) {
    Problem22.solve should be(871198282)
  }

  test("23: Find the sum of all the positive integers which cannot be written as the sum of two abundant numbers.", Tag("23")) {
    Problem23.solve should be(4179871)
  }

  test("24: What is the millionth lexicographic permutation of the digits 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?", Tag("24")) {
    Problem24.solve should be(2783915460L)
  }

  test("25: What is the first term in the Fibonacci sequence to contain 1000 digits?", Tag("25")) {
    Problem25.solve should be(4782)
  }

  test("26: Find the value of d  1000 for which 1/d contains the longest recurring cycle in its decimal fraction part", Tag("26")) {
    Problem26.solve should be(983)
  }

  test("27: Find the product of the coefficients, a and b, for the quadratic expression that produces the maximum number of primes for consecutive values of n, starting with n = 0", Tag("27")) {
    Problem27.solve should be(-59231)
  }

  test("28: What is the sum of the numbers on the diagonals in a 1001 by 1001 spiral formed in the same way?", Tag("28")) {
    Problem28.solve should be(669171001)
  }

  test("29: How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?", Tag("29")) {
    Problem29.solve should be(9183)
  }

  test("30: Find the sum of all the numbers that can be written as the sum of fifth powers of their digits", Tag("30")) {
    Problem30.solve should be(443839)
  }

  test("31: How many different ways can £2 be made using any number of coins?", Tag("31")) {
    Problem31.solve should be(73682)
  }

  test("32: Find the sum of all products whose multiplicand/multiplier/product identity can be written as a 1 through 9 pandigital.", Tag("32")) {
    Problem32.solve should be(45228)
  }

}

